name: release

on:
  push:
    tags: ["v*.*.*"]

env:
  IMAGE_NAME: node_server
  REGISTRY: ghcr.io
  PACKAGE_PATH: porthorian/teaburys
  BUILD_VERSION: ${{ github.ref_name }}

permissions:
  packages: write

jobs:
  build:
    name: Build and Release Container Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Tag
        run: |
          echo "TAG=${{ env.REGISTRY }}/${{ env.PACKAGE_PATH }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_VERSION }}" >> $GITHUB_ENV
      - name: Build Image
        run: |
          docker build \
          --tag ${{ env.TAG }} \
          .
      - name: Publish Image
        run: |
          docker push ${{ env.TAG }}
